<a href="https://colab.research.google.com/github/Adykey79/deep-learning-challenge/blob/main/Deep_Learning_Challenge/AlphabetSoupCharity_Optimization_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Supress Warnings
import warnings
warnings.simplefilter(action = "ignore")

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop( ['EIN','NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df_unique = application_df.nunique().sort_values()
print(application_df_unique)

STATUS                       2
SPECIAL_CONSIDERATIONS       2
IS_SUCCESSFUL                2
ORGANIZATION                 4
USE_CASE                     5
AFFILIATION                  6
INCOME_AMT                   9
APPLICATION_TYPE            17
CLASSIFICATION              71
ASK_AMT                   8747
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value
# create a list of application types to be replaced
# use the variable name `application_types_to_replace`

APPLICATION_TYPE_CUTOFF = 500

application_type_replace_filter_series = application_df["APPLICATION_TYPE"].value_counts() < APPLICATION_TYPE_CUTOFF
application_type_replace_filter_series

APPLICATION_TYPE
T3     False
T4     False
T6     False
T5     False
T19    False
T8     False
T7     False
T10    False
T9      True
T13     True
T12     True
T2      True
T25     True
T14     True
T29     True
T15     True
T17     True
Name: count, dtype: bool

In [6]:
application_types_to_replace = application_df["APPLICATION_TYPE"].value_counts()[application_type_replace_filter_series].index

In [7]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [8]:
application_df.loc[25:50]

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
25,T4,Independent,C3000,ProductDev,Trust,1,0,N,5000,1
26,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,1
27,T3,CompanySponsored,C2000,Preservation,Trust,1,25000-99999,N,44004,1
28,T3,CompanySponsored,C2000,Preservation,Trust,1,0,N,5000,0
29,T6,Independent,C2000,ProductDev,Trust,1,0,N,5000,1
30,T6,Independent,C2000,ProductDev,Trust,1,100000-499999,N,323466,1
31,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
32,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
33,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,1
34,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,0
35,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,0
36,T4,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
37,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
38,T7,Independent,C1000,ProductDev,Association,1,0,N,5000,0
39,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,5000,1
40,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,709815,0
41,Other,Independent,C1000,ProductDev,Trust,1,25000-99999,N,1329410,0
42,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
43,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,0
44,T3,Independent,C7200,Preservation,Trust,1,0,N,5000,1
45,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
46,T3,CompanySponsored,C2000,Preservation,Trust,1,0,N,5000,0
47,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,0
48,T3,Independent,C1700,Preservation,Trust,1,0,N,5000,1
49,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,0
50,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31613,1

In [9]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_gt_1_filter_series = application_df['CLASSIFICATION'].value_counts()>1
application_df['CLASSIFICATION'].value_counts()[classification_gt_1_filter_series]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

CLASSIFICATION_TYPE_CUTOFF = 100

classification_replace_filter_series = application_df["CLASSIFICATION"].value_counts() < CLASSIFICATION_TYPE_CUTOFF
classification_replace_filter_series
classifications_to_replace= application_df["CLASSIFICATION"].value_counts()[classification_replace_filter_series].index


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)

In [13]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies["IS_SUCCESSFUL"].values
X = application_df_dummies.drop('IS_SUCCESSFUL', axis=1)

In [14]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 78)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Optimizer No 1 - Compile, Train and Evaluate the Model

* Number of Hidden Layers = 3

* Number of Neurons for each Layer

* hidden_nodes_layer1 = 60

* hidden_nodes_layer2 = 25

* hidden_nodes_layer2 = 10

* Activation Function used = RELU

In [21]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 60
hidden_nodes_layer2 = 25
hidden_nodes_layer3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer1, activation = "relu", input_dim = number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2, activation = "relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer3, activation = "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 60)                3000

 dense_5 (Dense)             (None, 25)                1525

 dense_6 (Dense)             (None, 10)                260

 dense_7 (Dense)             (None, 1)                 11

=================================================================
Total params: 4796 (18.73 KB)
Trainable params: 4796 (18.73 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [22]:
# Compile the model
nn.compile(loss = "binary_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [23]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs = 100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5707 - accuracy: 0.7206
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7313
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5493 - accuracy: 0.7322
Epoch 4/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5472 - accuracy: 0.7349
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7334
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7355
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7352
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5440 - accuracy: 0.7353
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7358
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5423 - accuracy: 0.7367
Epoch 11/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5419 - accuracy: 0.7364
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7357
Epoch 13/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7370
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7372
Epoch 15/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 16/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5404 - accuracy: 0.7372
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5398 - accuracy: 0.7377
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7379
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7393
Epoch 20/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5392 - accuracy: 0.7388
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7390
Epoch 22/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5386 - accuracy: 0.7387
Epoch 23/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5383 - accuracy: 0.7386
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7386
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7397
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7402
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7397
Epoch 28/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7395
Epoch 29/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5374 - accuracy: 0.7394
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7400
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7393
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7405
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7398
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5368 - accuracy: 0.7401
Epoch 35/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5369 - accuracy: 0.7397
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7398
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7396
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7403
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5361 - accuracy: 0.7408
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7403
Epoch 41/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5358 - accuracy: 0.7409
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7397
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7398
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7409
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7402
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7400
Epoch 47/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7402
Epoch 48/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5352 - accuracy: 0.7401
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7407
Epoch 50/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5351 - accuracy: 0.7407
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5347 - accuracy: 0.7402
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7400
Epoch 53/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7400
Epoch 54/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5346 - accuracy: 0.7404
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7411
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5343 - accuracy: 0.7406
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7405
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7420
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5347 - accuracy: 0.7404
Epoch 60/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5343 - accuracy: 0.7406
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5338 - accuracy: 0.7419
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7412
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7410
Epoch 64/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5340 - accuracy: 0.7413
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5337 - accuracy: 0.7399
Epoch 66/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5341 - accuracy: 0.7412
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7406
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7404
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7403
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7411
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7413
Epoch 72/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5337 - accuracy: 0.7409
Epoch 73/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5334 - accuracy: 0.7411
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7414
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7412
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7422
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7412
Epoch 78/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5334 - accuracy: 0.7420
Epoch 79/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5330 - accuracy: 0.7407
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7409
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7418
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7415
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7423
Epoch 85/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5333 - accuracy: 0.7411
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7419
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7416
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5328 - accuracy: 0.7416
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7423
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 91/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5324 - accuracy: 0.7419
Epoch 92/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5328 - accuracy: 0.7419
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5324 - accuracy: 0.7418
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7417
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7421
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7414
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5321 - accuracy: 0.7417
Epoch 98/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5317 - accuracy: 0.7412
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5325 - accuracy: 0.7412
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7423

In [24]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5560 - accuracy: 0.7261 - 759ms/epoch - 3ms/step
Loss: 0.5559778213500977, Accuracy: 0.726064145565033

In [25]:
# Export our model to HDF5 file
from google.colab import files
nn.save("AlphabetSoupCharity_Optimization-2.h5")
files.download("AlphabetSoupCharity_Optimization-2.h5")

Attemp Number 2 To Optimise the Model To Acheive Accuracy Higher than 75%

## Result:

* Making above changes to the model displays the accuracy of 72%.