<a href="https://colab.research.google.com/github/Adykey79/deep-learning-challenge/blob/main/Deep_Learning_Challenge/AlphabetSoupCharity_Optimization_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

# Supress Warnings
import warnings
warnings.simplefilter(action = "ignore")

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop( ['EIN', 'NAME'], axis= 1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df_unique = application_df.nunique().sort_values()
print(application_df_unique)

STATUS                       2
SPECIAL_CONSIDERATIONS       2
IS_SUCCESSFUL                2
ORGANIZATION                 4
USE_CASE                     5
AFFILIATION                  6
INCOME_AMT                   9
APPLICATION_TYPE            17
CLASSIFICATION              71
ASK_AMT                   8747
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value
# create a list of application types to be replaced
# use the variable name `application_types_to_replace`

APPLICATION_TYPE_CUTOFF = 150

application_type_replace_filter_series = application_df["APPLICATION_TYPE"].value_counts() < APPLICATION_TYPE_CUTOFF
application_type_replace_filter_series

APPLICATION_TYPE
T3     False
T4     False
T6     False
T5     False
T19    False
T8     False
T7     False
T10    False
T9     False
T13     True
T12     True
T2      True
T25     True
T14     True
T29     True
T15     True
T17     True
Name: count, dtype: bool

In [6]:
application_types_to_replace = application_df["APPLICATION_TYPE"].value_counts()[application_type_replace_filter_series].index

In [7]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
T9         156
Other      120
Name: count, dtype: int64

In [8]:
application_df.loc[25:50]

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
25,T4,Independent,C3000,ProductDev,Trust,1,0,N,5000,1
26,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,1
27,T3,CompanySponsored,C2000,Preservation,Trust,1,25000-99999,N,44004,1
28,T3,CompanySponsored,C2000,Preservation,Trust,1,0,N,5000,0
29,T6,Independent,C2000,ProductDev,Trust,1,0,N,5000,1
30,T6,Independent,C2000,ProductDev,Trust,1,100000-499999,N,323466,1
31,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,1
32,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
33,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,1
34,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,0
35,T3,Independent,C1200,Preservation,Trust,1,0,N,5000,0
36,T4,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
37,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
38,T7,Independent,C1000,ProductDev,Association,1,0,N,5000,0
39,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,5000,1
40,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,709815,0
41,Other,Independent,C1000,ProductDev,Trust,1,25000-99999,N,1329410,0
42,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,1
43,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,0
44,T3,Independent,C7200,Preservation,Trust,1,0,N,5000,1
45,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,1
46,T3,CompanySponsored,C2000,Preservation,Trust,1,0,N,5000,0
47,T7,Independent,C1000,ProductDev,Trust,1,0,N,5000,0
48,T3,Independent,C1700,Preservation,Trust,1,0,N,5000,1
49,T3,Independent,C1000,Preservation,Trust,1,0,N,5000,0
50,T3,Independent,C1000,Preservation,Trust,1,100000-499999,N,31613,1

In [9]:
# Look at CLASSIFICATION value counts for binning
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_gt_1_filter_series = application_df['CLASSIFICATION'].value_counts()>1
application_df['CLASSIFICATION'].value_counts()[classification_gt_1_filter_series]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
CLASSIFICATION_TYPE_CUTOFF = 1000

classification_replace_filter_series = application_df["CLASSIFICATION"].value_counts() < CLASSIFICATION_TYPE_CUTOFF
classification_replace_filter_series
classifications_to_replace= application_df["CLASSIFICATION"].value_counts()[classification_replace_filter_series].index


# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_dummies = pd.get_dummies(application_df)

In [13]:
# Split our preprocessed data into our features and target arrays
y = application_df_dummies["IS_SUCCESSFUL"].values
X = application_df_dummies.drop('IS_SUCCESSFUL', axis=1)

In [14]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Optimizer No 1 - Compile, Train and Evaluate the Model

* Number of Hidden Layers = 2

* Number of Neurons for each Layer

* hidden_nodes_layer1 = 40

* hidden_nodes_layer2 = 15

* Activation Function used = RELU

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 40
hidden_nodes_layer2 = 15

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_nodes_layer1, activation= "relu", input_dim= number_input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_nodes_layer2, activation= "relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation= "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 40)                1800

 dense_1 (Dense)             (None, 15)                615

 dense_2 (Dense)             (None, 1)                 16

=================================================================
Total params: 2431 (9.50 KB)
Trainable params: 2431 (9.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# Compile the model
nn.compile(loss= "binary_crossentropy", optimizer= "adam", metrics= ["accuracy"])

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs= 100)

Epoch 1/100
804/804 [==============================] - 7s 6ms/step - loss: 0.5881 - accuracy: 0.7083
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5558 - accuracy: 0.7286
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5523 - accuracy: 0.7306
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5506 - accuracy: 0.7308
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7318
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5482 - accuracy: 0.7330
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7326
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7327
Epoch 9/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7343
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5458 - accuracy: 0.7340
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7349
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5453 - accuracy: 0.7357
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5446 - accuracy: 0.7348
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7362
Epoch 15/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5441 - accuracy: 0.7355
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7359
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5433 - accuracy: 0.7354
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5433 - accuracy: 0.7350
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7364
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5431 - accuracy: 0.7359
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5426 - accuracy: 0.7372
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7368
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7365
Epoch 24/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7370
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5420 - accuracy: 0.7374
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5419 - accuracy: 0.7372
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7378
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7372
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7374
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7382
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7372
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7378
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7381
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5409 - accuracy: 0.7377
Epoch 35/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5405 - accuracy: 0.7376
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7357
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5404 - accuracy: 0.7376
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5405 - accuracy: 0.7376
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7375
Epoch 40/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7379
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7382
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7388
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7384
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5398 - accuracy: 0.7383
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7379
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7371
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5397 - accuracy: 0.7383
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7384
Epoch 49/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7372
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7379
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7382
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5394 - accuracy: 0.7377
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7380
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7384
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7380
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7386
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7388
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7381
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7377
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7383
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7393
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7380
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7379
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7388
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7392
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7386
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5378 - accuracy: 0.7385
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7389
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7394
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7383
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7392
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7392
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7381
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7388
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7395
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7390
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5375 - accuracy: 0.7390
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7376
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7387
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7377
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7387
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7392
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7395
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5372 - accuracy: 0.7387
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7383
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7396
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7392
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7388
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7387
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7388
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7394
Epoch 93/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7392
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7385
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7397
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7386
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7393
Epoch 99/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7389
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7398

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5568 - accuracy: 0.7283 - 498ms/epoch - 2ms/step
Loss: 0.5567776560783386, Accuracy: 0.7282798886299133

In [20]:
# Export our model to HDF5 file
from google.colab import files
nn.save("AlphabetSoupCharity_Optimization-1.h5")
files.download("AlphabetSoupCharity_Optimization-1.h5")

## Result:
* Attemp Number 1 To Optimise the Model To Acheive Accuracy Higher than 75%
* There was no noticeable change in the first attempt.